### ISSUE TITLE
Einigung auf Übersetzungen, Abkürzungen usw.

### ISSUE THREAD

**Issue by u-n-known** [javascript-tutorial/de.javascript.info#19]
Ich würde vorschlagen **ein Referenzdokument** zu erstellen welches 

1. abzukürzende Wörter und
2. nicht zu übersetzende englische Wörter 

festlegt. **Ersteres** weil es den Lesefluss vereinfacht. Begegnet ein Leser den selben Abkürzungen fördert das dessen Lesefluss. Hier muss auch die WZR-Setzung (Weißzeichenraum) definiert werden. **Zweiteres** weil, der entscheidenden Entwicklung von Computertechnik in den Vereinigten Staaten geschuldet, es gewisse Wörter gibt die schwer bis gar nicht mit einer Übersetzung ins Deutsche das englische Äquivalent ausdrücken können. Die englischen Wörter, wenn vertretbar übersetzbar, sollten meiner Meinung nach dem Deutschen Wort  @innerhalb von Klammern und in kursiv trotzdem nachgestellt werden um die Englischkenntnisse im Bereich der IT von Laien zu verbessern und in der Hoffnung dadurch Personen die Orientierung in Onlineforen zu erleichtern. Hinzu kommt ggf. eine Verlinkung zu deutschen Wikipediaartikeln zum betreffenden Subjekt, vor allem bei Wörtern die nicht übersetzbar sind. 
Wörter die nicht übersetzt werden müssen da sie keine tiefgreifende Englischkenntnisse fordern oder der deutschen Übersetzung so nah sind – bspw. _Hello_ – sollten meiner Meinung nach auch immer kursiv gestellt werden.

**Comment by christianhegedues** [comment]
Um das mal nicht unkommentiert stehen zu lassen:

Leider finde ich, dass Abkürzungen überhaupt nicht den Lesefluss fördern. Besonders dann nicht, wenn es sich um unbekannte Abkürzungen handelt, die vorher erst erlernt werden müssen. Da es sich hier um eine Übersetzung eines englischen Originals handelt, sollten Abkürzungen auch nur dann vorkommen, wenn sie im Original stehen. Den Text soweit es geht unverändert zu lassen und hier nicht ein eigenes Süppchen zu kochen, hat auch ein bisschen was mit Wertschätzung gegenüber den Autor des Originals zu tun.

Zum zweiten Punkt kann ich nur Vorschlagen, es so zu behandeln, wie es in der Readme des Repositories steht. Zudem finde ich es persönlich ein bisschen viel, zu jedem Fachausdruck das englische Äquivalent in Klammer dazuzuschreiben z.B. Funktionen (*functions*). Als Leser weiß ich hier eventuell gar nicht, was man mir mitteilen möchte, da ich es weder lesen noch aussprechen kann und im Text aus nirgends steht, dass es sich hierbei um die englische Übersetzung handelt.

**Comment by u-n-known** [comment]
@christianhegedues Vielen Dank erstmals für die Rückmeldung. 

Ich hatte jetzt _einige_ Zeit über das Geschriebene nachzudenken. Beim zweiten Punkt kann ich nur zustimmen. Ich habe das im Readme schlicht übersehen.
 Zu ersterem fällt mir nicht mehr ein, als dass sich dies im Laufe der Übersetzung zeigen wird wo Abkürzungen überhaupt angebracht und sinnvoll sind. Letztendlich will ich meine Forderungen zurücknehmen, denn ein verbindliches Referenzdokument wäre nichts weiteres als eine Last, die den Übersetzungsprozess und den Spaß daran mindern würde. 
 Verbesserungen um den Lesefluss zu steigern wie durch Etablierung eines einheitlichen Schreibstils können erst stattfinden nachdem das ganze Dokument übersetzt vorliegt, denn erst dann lässt es sich in einem Fluss lesen, der evtl. noch viele Kurven schlägt und Wasserfälle trägt.
